### ISSUE TITLE
Fix warnings in PHP 7.x

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/beautytips#6]
I'm using Beautytips on two websites, one is running on PHP 7.2, the other one *was* running on PHP 7.1 (in the meantime also upgraded to 7.2).

With PHP 7.1 I saw the following warning in DBlog:

> Invalid argument supplied for foreach() in beautytips_init() (line 17 of /(...)/modules/beautytips/beautytips.module).

With PHP 7.2 I see the same, plus this one:

> count(): Parameter must be an array or an object that implements Countable in beautytips_init() (line 16 of /(...)/modules/beautytips/beautytips.module).

---

PR by @olafgrabienski: https://github.com/backdrop-contrib/beautytips/pull/7

**Comment by olafgrabienski** [comment]
I've searched the web for the "count" warning and found a similar issue in the Drupal *Bootstrap* theme, cf. https://www.drupal.org/project/bootstrap/issues/2999011.

There is a patch in [comment 9 of the issue](https://www.drupal.org/project/bootstrap/issues/2999011#comment-12775139), which replaces `count` by `!empty`, so out of curiosity I tried to use the same fix in Beautytips. Changing the code as shown below, both errors disappear. That said, as a non PHP coder, I don't have the minimal idea what's happening there. @Graham-72 What do you think about it?

line 16:
`- if (count($selectors)) {`
`+ if (!empty($selectors)) {`

line 94:
`- if (count($options)) {`
`+ if (!empty($options)) {`

line 187:
`- if (count($styles['default'])) {`
`+ if (!empty($styles['default'])) {`

line 193f:
`- if (count($value)) {`
`+ if (!empty($value)) {`

**Comment by olafgrabienski** [comment]
@Graham-72 I've talked with a friend, and he supports the approach mentioned above, so I've made a pull request. Can you have a look at it?

**Comment by Graham-72** [comment]
@olafgrabienski I'm sorry for the delay in responding to this issue. Yes, there is a problem because the module is often using count() in order to check whether a variable is an array with any elements and this is no longer acceptable with PHP7.2 hence the warnings. It seems that !empty() should be used, and in more places than you have identified so I will add another PR.
Also, I have made mistakes in my porting when creating the default config file for the module. An empty array should I think be given as `"beautytips_added_selectors_array": [],` and not `"beautytips_added_selectors_array": '',` and so I will add a PR for this.

**Comment by olafgrabienski** [comment]
@Graham-72 No problem, and thanks for merging the PR!

I'd not looked for other files where `count()` is used, since the errors on my testing site disappeared already with the PR. Maybe the other places are less used. Are you up to add the other PR? If you don't have time, I could also try to do so.
